name: Code Push and Daily Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute make help
        run: |
          make help
