name: module3_task1

"on":
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: update
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: installation Hugo with script
        run: cd ./module3_task1 && ./setup.sh

      - name: Validate Makefile execution make build command
        run: |
          make help
          make build
          make run
          make stop
          make clean
        working-directory: module3_task1

